modLoader = "javafml" #mandatory
loaderVersion = "[39,)" #mandatory
issueTrackerURL = "https://github.com/Yamahari/ILikeWood-1.15/issues" #optional
license = "MIT"
[[mods]] #mandatory
modId = "ilikewood" #mandatory
version = "1.18.1-7.0.0.1" #mandatory
displayName = "I Like Wood" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL = "https://www.curseforge.com/minecraft/mc-mods/i-like-wood" #optional
logoFile = "logo.png" #optional
credits = "Yamahari and the people of Forge" #optional
authors = "Yamahari" #optional
description = '''
This mod adds wood variants for blocks that should have one but don't.
It also adds a new wood related blocks.
'''
[[dependencies.ilikewood]] #optional
# the modid of the dependency
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[39.0.5,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewood]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"